### ISSUE TITLE
您好，请问编译lru的时候，出现找不到python.h的错误，您是怎么解决的？这个是可以不编译的吗？

### ISSUE THREAD

**Issue by yjhuasheng** [anoymous-face/FFC#1]

**Comment by anoymous-face** [comment]
You can mannually set the directory that containing python.h in lru_c/CMakeList.txt using the following command`set(Python_INCLUDE_DIRS "${your anaconda home}/include/python3.7m")`. Or just skip compilation. Simply rename lru_python_impl.py to lru_utils.py as LRU is not the bottleneck of the training.

**Comment by yjhuasheng** [comment]
thank you very much！！！
